<a href="https://colab.research.google.com/github/braulioalda4-code/Metodos_numericosU5/blob/main/Tabla_de_diferencia_dividida.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejercicio 1 - Tabla de diferencia dividida

In [1]:
import numpy as np

x = np.array([1,2,3])
y = np.array([1,4,9])

n = len(x)

tabla = np.zeros((n,n))
tabla[:,0] = y

for j in range(1,n):
    for i in range(n-j):
        tabla[i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] - x[i])

print("Tabla de diferencias divididas:\n" + str(tabla))


Tabla de diferencias divididas:
[[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]
